### ISSUE TITLE
Fix hard-coded address widths to `APB_FPGA_ADDR_WIDTH`

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/core-v-mcu#108]
@gmartin102 noticed a number of other places where the width is hardcoded [19:0]. They should probably be fixed to be `APB_FPGA_ADDR_WIDTH` also. Please @gmartin102 if you could address that in a separate pull request?

Reference #107

**Comment by gmartin102** [comment]
@zarubaf I fixed a number of other address width issues in efpga_subsystem,  Also included some other logic fixes in various files and fixed a number of utility files .. openocd and  ioscript things.  I will do a pull request against Quicklogic branch address-width

**Comment by zarubaf** [comment]
Please do so! Thanks!

**Comment by gmartin102** [comment]
@zarubaf - I've executed a pull request, but it fails the verible format, but I can't tell why its complaining about.  I did run the format script and I had difficulting getting the git-diff script run locally so I'm not sure how to correct the errors

**Comment by zarubaf** [comment]
Sorry @gmartin102 I've missed the PR. I've left some minor comments there.

**Comment by MikeOpenHWGroup** [comment]
Hi @gmartin102, what is the status of this issue?

**Comment by MikeOpenHWGroup** [comment]
Complete.
