### ISSUE TITLE
Peripheral output enables from udma should be active high.

### ISSUE THREAD

**Issue by gmartin102** [openhwgroup/core-v-mcu#120]
the unified pad/pin mixing scheme assumes active high output enables.   in particular udma spa and stdio have dynamic output enables that are specified as active low. -- I will make a pull request to correct this.

**Comment by MikeOpenHWGroup** [comment]
Hi @gmartin102, what is the status of this issue?

**Comment by MikeOpenHWGroup** [comment]
Done
