### ISSUE TITLE
Behavior of debug module is not as expected

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-mcu#163]
During his review of #157, @jeremybennett reported that the "behavior of debug module is not as expected".  (See [here](https://github.com/openhwgroup/core-v-mcu/pull/157#pullrequestreview-728297605)).  Unfortunately, the changes requested were squashed in order to advance other work.   The purpose of this Issue is to ensure the problem reported is resolved on this repo.

**Comment by gmartin102** [comment]
@jeremybennett - Have you been able to verify if the dev branch is functioning properly?  If so can we close this issue?

**Comment by jeremybennett** [comment]
@gmartin102 Good news is that it all builds, bad news is that I got
```
$ ./testbench.exe 
Timescale 1ns / 1ns
%Error: mem_init/boot.mem:0: $readmem file not found
Aborting...
Aborted (core dumped)
```
I need to read all your instructions about what files I need where to get this to run. I'll continue looking at this later.

**Comment by jeremybennett** [comment]
Hmmm - looks to be some hard-coded directory dependencies. I'll continue with this later.

**Comment by gmartin102** [comment]
you will need to do a link of the mem_init directory from the  verilator model-lib into your verilator source directory. All the mem  files are included in the model-lib directory. Same procedure as you used for the boot.cde file except the mem files are placed into the model-lib directory along with all the mem files to avoid jtag downloads of large programs.

**Comment by jeremybennett** [comment]
@gmartin102 Thanks for your hint on MM. Builds and runs cleanly now :-)
