### ISSUE TITLE
IDCODE change to 0x10001602 causes OPENOCD to fail

### ISSUE THREAD

**Issue by gmartin102** [openhwgroup/core-v-mcu#168]
Openocd reports an invalid IDCODE of 0x10001602.  Seems It wants at least a "1" in the LSB position and the manufacturer code is illegal.

**Comment by zarubaf** [comment]
Indeed, I remember the LSB should be 1. I’ll fix that. For the other thing we need to patch openocd with the OpenHW IDCODE.

**Comment by gmartin102** [comment]
@zarubaf -- for a temporary fix, I am going to make the IDCODE 0x10001603 to make openocd happy, but That Manufacture code (0x301) seems to be assigned to MOVEKING -
Info : JTAG tap: riscv.cpu tap/device found: 0x10001603 (mfg: 0x301 (MOVEKING), part: 0x0001, ver: 0x1)
Do we have or need a Manufacture code or is that for the end users to assign?

**Comment by zarubaf** [comment]
Sorry @gmartin102: So our JEDEC code is `0x602` (as registered in JEP106). I think my misconception was that I thought the debug module would shift that appropriately. So the proper ID CODE should be:

`0x10001C05`

Can you check that, there should probably be unknown vendor and I will get the PR to OpenOCD (once I've figured out how that works).

![Screenshot 2021-09-07 at 16 02 42](https://user-images.githubusercontent.com/199415/132358241-01077e88-08ef-4ab4-be3c-de1c4bfe4582.png)

**Comment by zarubaf** [comment]
Can you try quickly and report back please?

**Comment by gmartin102** [comment]
Yes, will get back to you as soon as i can complete a P&R

**Comment by gmartin102** [comment]
@zarubaf 0x10001c05 works --
Info : JTAG tap: riscv.cpu tap/device found: 0x10001c05 (mfg: 0x602 (<unknown>), part: 0x0001, ver: 0x1)
Info : datacount=2 progbufsize=8
Info : Examined RISC-V core; found 1 harts

**Comment by gmartin102** [comment]
Yes I will make a pr from dev to master with that corrected and an additional correction to the ioscript later today

**Comment by MikeOpenHWGroup** [comment]
@gmartin102, can this issue be closed?

**Comment by zarubaf** [comment]
Added to OpenOCD
