### ISSUE TITLE
Some questions about EFPGA

### ISSUE THREAD

**Issue by kangliyu1** [openhwgroup/core-v-mcu#185]
Some questions about EFPGA
Hello! Is the role of EFPGA in CORE-V-MCU a configurable HWPE? Or can the EFPGA module be built into any circuit based on the given bitstream? Under the core-v-mcu project, I found that the SDK cannot be built like pulpissimo, so how should this EFPGA be used? Another question is that EFPGA does not seem to be open source in the core-v-mcu project. What are the characteristics of the EFPGA used in this project? (For example: how many LUTs are there), I hope some seniors can give some pointers, thank you very much! !

**Comment by MikeOpenHWGroup** [comment]
Hi @timsaxe, can you respond to this query?

**Comment by gmartin102** [comment]
Sorry about the late response.  but here is short paragraph (ulitmately destined for the documantaion package) abou the embedded FPGA
A Quicklogic ArcticPro 2 eFPGA with four math Blocks is equipped. The EFPGA contains approximately 1000 SLC each with 4 lut/ff elements. 2 Math units are provided, each math unit contains 3 4kx32 bit Dual port RAMs and 2 Multiplier units. the RAMS cna be configures to be 8/16/or 32 bit width independently on the read and write ports. The mulitpliers can be configured to be a 32x32, 2 -16x16, 4 8x8, or 8 4x4 multipliers. The EFPGA has a primary APB sytle interface to the SoC and can be addressed as a stadard peripheral. In addition the CPU controlled APB interface the EFPGA has access to 4 TCDM (Tightly Coupled Distributed Memory) interfaces that allow the EFPGA to independently read and write the System Memory. The EFPGA had 16 dedicated interrupt output signals to the SoC Event Generator along with 40 FPGAIO that can send and recieve data from the device PADs.

**Comment by MikeOpenHWGroup** [comment]
Hi @kangliyu1, for your information, the above has already been intergrated into a `documentation` branch that has yet to be merged onto the main branch of this repo.  ([link](https://github.com/openhwgroup/core-v-mcu/blob/documentation/docs/doc-src/CORE-V-MCU_User_Manual_Outline.md))

**Comment by kangliyu1** [comment]
@MikeOpenHWGroup @gmartin102 thank you very much！！
