### ISSUE TITLE
Consider using verible for linting and code formatting

### ISSUE THREAD

**Issue by mithro** [openhwgroup/core-v-mcu#20]
Hi!

It looks like this project is using the LowRISC style guide. You thus might be interested in [Google's verible project](https://github.com/google/verible) which provides an Apache 2.0 licensed SystemVerilog linter and code formatter with the LowRISC style guide as an early target!

Due to the permissive license, you can even run the linter on CI systems like Travis CI, GitHub actions or Azure Pipelines to check that your code stays in compliance!

Good luck with your project!

**Comment by MikeOpenHWGroup** [comment]
Ouch, I cannot believe we let this one get so stale.

@mithro, AFAIK we have been using Verible for this project since 2021-06 (see our [top-level README](https://github.com/openhwgroup/core-v-mcu#verible-format-check))

@gmartin102 and/or @zarubaf can you confirm?

**Comment by gmartin102** [comment]
Yes we are using verible linter as part of the CI scripts

**Comment by mithro** [comment]
@gmartin102 - You might be interested in the recent GitHub Actions we published @ https://github.com/chipsalliance/verible-linter-action and https://github.com/chipsalliance/verible-formatter-action which are talked about @ https://antmicro.com/blog/2021/08/verible-integration-with-github-actions/ -- They surface the lint and formatting changes in the GitHub Pull Request UI as shown below;
![image](https://user-images.githubusercontent.com/21212/140425609-cd18bab8-d0b0-4c6a-b7c6-50d44f558ce4.png)

**Comment by MikeOpenHWGroup** [comment]
Thanks @gmartin102!  Thanks @mithro - I'll be sure to that check out.
