### ISSUE TITLE
target_sim in fusesoc core file in cv32e40p is set to latch rf

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-mcu#207]
Question: not very familiar with fusesoc but, shouldn't the register file for simulation (and for everything else) be set to flip-flop?

https://github.com/openhwgroup/core-v-mcu/blob/master/rtl/vendor/openhwgroup_cv32e40p.core#L71

**Comment by gmartin102** [comment]
Yes this should be set for Register.  The synthesis path is using register also.
