### ISSUE TITLE
Verilator seems broken --

### ISSUE THREAD

**Issue by gmartin102** [openhwgroup/core-v-mcu#224]

**Comment by MikeOpenHWGroup** [comment]
Hi Greg.  Can you provide more information?

- What is the command-line you used?
- What is the error message?

**Comment by gmartin102** [comment]
@mike,
I might have been premature in my assessment, Making sure I have the correct verilator installed.  Due to the poor support of verilator in cocotb I need to use an previous version (4.106) for my other work.  I may have messed up my 4.210 installation and I need to rebuild it.
Greg


On Apr 11, 2022, at 8:17 PM, Mike Thompson ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Greg. Can you provide more information?

  *   What is the command-line you used?
  *   What is the error message?
