### ISSUE TITLE
Documentation link leads to out-of-date file

### ISSUE THREAD

**Issue by timsaxe** [openhwgroup/core-v-mcu#23]
# Template for CORE-V-MCU Issues

## Bug Title
The main readme.md refers to fpga/readme.md in the cmc repo which is not in sync

### Type
Documentation

### Steps to Reproduce
Go to main readme, click on following link:

~~~
Instructions to install the Core-v-mcu environment, instantiate the CV32E40P processor, and
build the FPGA platform are [here](https://github.com/hpollittsmith/core-v-mcu/tree/master/fpga).
~~~

### Additional context
The precise issue that I ran into is that the cmc version refers to configs/platform_fpga.sh when the file is actually named configs/platform-fpga.sh.  This is correct in the OHW repo.

**Comment by hpollittsmith** [comment]
Thanks, Tim. The link has been corrected.
