### ISSUE TITLE
[TASK] <MCU Manual: Memory Map>

### ISSUE THREAD

**Issue by DBees** [openhwgroup/core-v-mcu#254]
### Is there an existing core-v-mcu task for this?

- [X] I have searched the existing task issues

### Task Description

Create memory map section of User Manual. 

### Description of Done

Accepted pull request to documentation2 branch including memory map with following components:
Boot Rom
RAM
Peripherals
Debug
eFPGA

**Comment by MikeOpenHWGroup** [comment]
This task can be closed now.  The above content is now available in the [CORE-V-MCU User Manual](https://docs.openhwgroup.org/projects/core-v-mcu/doc-src/mmap.html#memory-map) on the master branch.
