### ISSUE TITLE
[TASK] <MCU manual:  System Control Peripherals >

### ISSUE THREAD

**Issue by DBees** [openhwgroup/core-v-mcu#257]
### Is there an existing core-v-mcu task for this?

- [X] I have searched the existing task issues

### Task Description

Create the section of the user manual which describes the peripherals listed below

### Description of Done

Accepted pull request to documentation2 branch describing the following:
Watchdog TImer
GPIO
IO Mux and GPIO Introduction
IO Mux Overview
How to Select Output Function
Selecting an Input Function
IOMux Assignments
GPIO Registers
Soft Reset

**Comment by MikeOpenHWGroup** [comment]
Due to the restructuring of the CORE-V-MCU User Manual, this task is out of date.  I will close it and remove it from the project.
