### ISSUE TITLE
[TASK] <MCU Manual: MCU Summary>

### ISSUE THREAD

**Issue by DBees** [openhwgroup/core-v-mcu#264]
### Task Description

Create pull request on documentation2 branch covering a 1 paragraph summary of the MCU

### Description of Done

Accepted pull request covering above

**Comment by MikeOpenHWGroup** [comment]
After the re-organization of the CORE-V-MCU User Manual, this task is out-of-date and no longer required.  I will close the issue and delete it from the project board.
