### ISSUE TITLE
README.md error

### ISSUE THREAD

**Issue by athurwo** [openhwgroup/core-v-mcu#267]
### Is there an existing core-v-mcu bug for this?

- [X] I have searched the existing bug issues

### Bug Description

In the README.md,   description is "genesys2-emul",   but is "genesys-emul" in Makefile.

**Comment by MikeOpenHWGroup** [comment]
Thanks for the bug report @athurwo.  Pull-request #269 will resolve it.

**Comment by MikeOpenHWGroup** [comment]
PR #269 has been merged to master.

@athurwo, please confirm the update and close this issue if it is resolved.  Thanks!
