### ISSUE TITLE
How to totally customize UDMA subsystem with pulp_soc_defines header file ?

### ISSUE THREAD

**Issue by WazaAbdulkadir** [openhwgroup/core-v-mcu#307]
pulp_soc_defines header file could be used to customize peripherals. 
Via setting 0 for SDIO and CAM peripheral as in the image: 

![image](https://github.com/openhwgroup/core-v-mcu/assets/47847116/f2daf29f-3f87-49bd-82e7-16a4c327f317)

I was able to remove them from uDMA subsytem and generate bitstream. 
But when I tried to remove one of the I2Cm or QSPI peripherals I got error and couldn't run `make nexys-emul`. 

So if I write 0 instead of 'N_QSPIM, 'N_I2CM or 'N_I2SC in the above image ioscript.py script does not work.

What could be the reason behind this?

**Comment by MikeOpenHWGroup** [comment]
Hi @WazaAbdulkadir, thanks for your interest.  The reconfigurability of the CORE-V-MCU has been depreciated and the `ioscript` is no longer supported.  (One of these days we need to remove this entirely from the repo).
