### ISSUE TITLE
Question: Which version of OpenOCD should be used with Core-V-MCU and CV32E40P

### ISSUE THREAD

**Issue by CLappin** [openhwgroup/core-v-mcu#330]
Hi all,

Which version of openocd should be used with the [pulp debugger](https://github.com/pulp-platform/riscv-dbg).

I've tried the latest version which doesn't connect correctly, I've also tried the 0.10.0 version that I had which seemed to all connection via telnet. 

Any help would be great ,
Thanks,
Ciaran

**Comment by MikeOpenHWGroup** [comment]
I have 0.12.0 installed on my Ubuntu machine.   The only additional support we can offer is what is written in the [Quick Start Guide](https://github.com/openhwgroup/core-v-mcu/blob/master/emulation/quickstart/README.md#core-v-mcu-quick-start-guide).

**Comment by CLappin** [comment]
Thank you @MikeOpenHWGroup  and  @gmartin102 . 
I'll take a look at the Quick Start .
