### ISSUE TITLE
running hello application for ZedBoard FPGA ( no thing displayed with  screen /dev/ttyUSB0 115200)

### ISSUE THREAD

**Issue by mohamedElbouazzati** [openhwgroup/core-v-mcu#54]
### Configuration 

- PULP-RISCV-TOOLCHAIN ( Pre-built) 
- PULP-SDK 
- Processor : CV32E40P
- Soc : Pulpissimo 
- Board: ZedBoard FPGA

### JTAG and UART Connections: 

| JTAG Signal | PMOD Pin |
|-------------|----------|
| TMS         | JA1      |
| TDI         | JA2      |
| TDO         | JA3      |
| TCK         | JA4      |
| GND         | JA5      |
| VCC (trgt)  | JA6      |

| UART Signal | PMOD Pin |
|-------------|----------|
| RXD         | JA7      |
| TXD         | JA8      |
| RTS         | JA9      |
| CTS         | JA10     |
| GND         | JA11     |

### C Program 

![test](https://user-images.githubusercontent.com/62422381/112665742-a9fc8980-8e5b-11eb-9bc9-df45538fd354.PNG)

### Openocd

![openocd](https://user-images.githubusercontent.com/62422381/112665826-c13b7700-8e5b-11eb-944a-451e8a5cb2e0.PNG)
### GDB 

![gdb](https://user-images.githubusercontent.com/62422381/112666092-12e40180-8e5c-11eb-99c8-2a5d16d5d031.PNG)

### screen /dev/ttyUSB0 115200

![screen](https://user-images.githubusercontent.com/62422381/112666114-1a0b0f80-8e5c-11eb-8912-f35158108bfc.PNG)

I don't know why nothing is displayed on the screen. 
Any suggestions are appreciated 
Thanks!

**Comment by zarubaf** [comment]
That is probably better asked at the PULPIssimo issue tracker. We are trying to detach from the PULP SDK and things are currently heavily in flux. Sorry for the inconvenience!
