### ISSUE TITLE
Remove `hwpe`

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/core-v-mcu#63]
I'd like to get your input on removing the `hwpe`. Are you using it in QuickLogic @timsaxe?

Further input requested from @davideschiavone @gmartin102.

**Comment by timsaxe** [comment]
Not using it. Personally I prefer removing unused stuff unless it has a clear fit to a future mission and that mission is well enough understood that you know the element is fit for that purpose.

From: Florian Zaruba ***@***.***>
Sent: Saturday, April 10, 2021 7:10 AM
To: openhwgroup/core-v-mcu ***@***.***>
Cc: Tim Saxe ***@***.***>; Mention ***@***.***>
Subject: [openhwgroup/core-v-mcu] RFC: Remove `hwpe` (#63)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

I'd like to get your input on removing the hwpe. Are you using it in QuickLogic @timsaxe<https://github.com/timsaxe>?

Further input requested from @davideschiavone<https://github.com/davideschiavone> @gmartin102<https://github.com/gmartin102>.

**Comment by zarubaf** [comment]
Great, completely agree!
