### ISSUE TITLE
RFC: Remove `scm`

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/core-v-mcu#65]
Is the SCM (standard-cell memory) actually needed? Are you looking for such features @timsaxe?

@davideschiavone do you happen to know more, whats your take?

**Comment by timsaxe** [comment]
Have not investigated this.  Do not have an opinion.

**Comment by zarubaf** [comment]
Apparently, it wasn't used anywhere so I've removed it for now. We can add (and discuss) whether/when this is needed.

**Comment by timsaxe** [comment]
Perfect.  We can let need drive us in the future.

**Comment by davideschiavone** [comment]
definitively to be removed. it was part of Quentin tape out from 2017
