### ISSUE TITLE
Open-source Quicklogic modules

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/core-v-mcu#67]
Currently, we are missing a couple of Quicklogic modules: 

https://github.com/openhwgroup/core-v-mcu/blob/f558efb9f6e0c73ebe7ddfb678058f3ab6e4af80/rtl_list.yml#L95-L99

@timsaxe and team, I'd like to have your input on this: 

- Can we open source this? Or is it proprietory?
- If we can't how can we make a behavioral module for those components or stub the FPGA?

As soon as we have an agreement we can proceed with a further issue.

**Comment by timsaxe** [comment]
We can opensource both the fcb and math units.

From: Florian Zaruba ***@***.***>
Sent: Saturday, April 10, 2021 7:19 AM
To: openhwgroup/core-v-mcu ***@***.***>
Cc: Tim Saxe ***@***.***>; Mention ***@***.***>
Subject: [openhwgroup/core-v-mcu] RFC: Quicklogic modules (#67)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Currently, we are missing a couple of Quicklogic modules:

https://github.com/openhwgroup/core-v-mcu/blob/f558efb9f6e0c73ebe7ddfb678058f3ab6e4af80/rtl_list.yml#L95-L99

@timsaxe<https://github.com/timsaxe> and team, I'd like to have your input on this:

  *   Can we open source this? Or is it proprietory?
  *   If we can't how can we make a behavioral module for those components or stub the FPGA?

As soon as we have an agreement we can proceed with a further issue.

**Comment by zarubaf** [comment]
Perfect @timsaxe! That is definitely the easiest and best solution!

**Comment by gmartin102** [comment]
I can add the missing files... seems like I can add to the Quicklogic fork which is called core-v-mcu-ohw in the QuickLogic-Corp area.  If this is ok or a better idea exists, let me know
