### ISSUE TITLE
Verilator testbench bring-up

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/core-v-mcu#91]
I am creating this tracking issue to see how we can bring up the Verilator testbench. @jeremybennett if you can point me towards the GDB resources that could be very helpful.

**Comment by jeremybennett** [comment]
We'll be using Embdebug, probably layered on OpenOCD. I can't give you a good link for Embdebug because we are in the process of a major release. This project will actually be part of the validation of that release.

**Comment by MikeOpenHWGroup** [comment]
@jeremybennett, I _believe_ this issue can be closed, is that correct?

**Comment by jeremybennett** [comment]
This is now working just fine. The issue can be closed.
