### ISSUE TITLE
Bring-up fusesoc FPGA support

### ISSUE THREAD

**Issue by zarubaf** [openhwgroup/core-v-mcu#94]
Fusesoc comes with pretty nice FPGA support. That would also help to target different FPGA boards with less code duplication. Things to figure out:

- How we can generate the IPs as part of the fusesoc flow (if this is at all necessary): olofk/fusesoc#505
- How to parameterize the platform and fpga: https://github.com/fusesoc/blinky/blob/1563da51e7169dfc993c1603b88b838f51556ada/blinky.core

**Comment by zarubaf** [comment]
I think that is implemented now, right @gmartin102?

**Comment by MikeOpenHWGroup** [comment]
@gmartin102 reports that this is done.
